define({
		queries:"פעולות תשאול",
		addNew: "הוסף חדש",
		setSource: "הגדר",
		setDataSource: "הגדר מקור נתונים",
		name: "שם",
		querySource: "מקור נתונים",
		queryName:"שם משימה",
		queryDefinition:"הגדרת מסנן",
		resultsSetting:"הגדרת תוצאות",
		symbolSetting:"הגדרות סימבול",
		resultSettingTip: "הגדר אילו תוצאות פלט להציג ואיך להציג אותן.",
		resultItemTitle:"כותרת פריט תוצאה",
		resultItemContent:"תוכן פריט תוצאה",
		fieldsSetTip:"סמן את השדות שאתה רוצה להציג. בחר שדה כדי לעדכן את הכינוי, הסדר והתבנית שלו.",
		addField:"הוסף שדה",
		visibility:"ניראות",
		alias:"שם נוסף",
		specialType:"סוג מיוחד",
		actions:"פעולות",
		none:"ללא",
		link:"קישור",
		image:"תמונה",
		noField:"אין שדה",
		operationalLayerTip:"הוסף תוצאה כשכבה תפעולית",
		setLayerSymbolTip:"הגדר את הסמל לתוצאת השאילתה: ",
		setSelectedSymbolTip:"הגדר סמל לישות הנבחרת.",
		notUseFilter:"אל תשתמש במסנן.",
		setSourceTip:"הגדר מקור שאילתה.",
		setFilterTip:"הגדר את המסנן בצורה תקינה.",
		ok:"אישור",
		cancel:"ביטול",
		noFilterTip: "מבלי להגדיר ביטוי מסנן, משימת שאילתה זו תפרט את כל התכונות במקור הנתונים שצוין."
});