define({
	root: {
		layers:"Layers",
		addNew: "Add New",
		setSource: "Set",
		setDataSource: "Set Data Source",
		name: "Name",
		querySource: "Data Source",
		queryName:"Layer Name",
		orderField: "Results Order Field",
		orderFieldTip:"Select a field that the results will be ordered by in the list.",
		queryDefinition:"Filter Definition",
		resultsSetting:"Results Setting",
		symbolSetting:"Symbol Setting",
		resultSettingTip: "Define what and how to display the output results.",
		resultItemTitle:"Result Item Title",
		resultItemOrder:"Order Results By",
		resultItemContent:"Result Item Contents",
		fieldsSetTip:"Check the fields you want to display. Select a field to update its alias, order, and format.",
		addField:"Add Field",
		visibility:"Visibility",
		alias:"Alias",
		specialType:"Special Type",
		actions:"Actions",
		none:"None",
		link:"Link",
		image:"Image",
		area:"Area",
		noField:"No field",
		operationalLayerTip:"Add result as operational layer",
		setLayerSymbolTip:"Set symbol for query results: ",
		setSelectedSymbolTip:"Set symbol of selected feature.",
		notUseFilter:"Don't use filter",
		setSourceTip:"Please set query source.",
		setFilterTip:"Please set filter correctly.",
		ok:"OK",
		cancel:"Cancel",
		noFilterTip: "Without filter expression defined, this query task will list all features in the specified data source."
	},
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});