define({
  root: {
    _widgetLabel: "Locate Features",
    selectLayerTip: "Click one of the layers to view available features.",
    invalidConfig: "Invalid configuration. Please use Query setting page to get correct configuration.",
    queryParams: "Options",
    layers: "LAYERS",
    features: "FEATURES",
    parameters: "OPTIONS",
    queries: "QUERIES",
    apply: "APPLY",
    layerFeatures: "Features",
    featureResults: "Results",
    queryResults: "Results",
    clear: "Clear",
    center: "Center",
    zoomTo: "Zoom To",
    noResults: "No feature found.",
    queryError: "Query failed !",
    numberFound: "Number of features found",
    mapExtentTip:"Limit the results to the current map extent.",
    noValue:"No value",
    and:"and",
    stringOperatorIs: "is", // e.g. <stringFieldName> is 'California'
    stringOperatorIsNot: "is not",
    stringOperatorStartsWith: "starts with",
    stringOperatorEndsWith: "ends with",
    stringOperatorContains: "contains",
    stringOperatorDoesNotContain: "does not contain",
    stringOperatorIsBlank: "is blank",
    stringOperatorIsNotBlank: "is not blank",
    dateOperatorIsOn: "is on", // e.g. <dateFieldName> is on '1/1/2012'
    dateOperatorIsNotOn: "is not on",
    dateOperatorIsBefore: "is before",
    dateOperatorIsAfter: "is after",
    dateOperatorDays: "days",
    dateOperatorWeeks: "weeks", // e.g. <dateFieldName> is the last 4 weeks
    dateOperatorMonths: "months",
    dateOperatorInTheLast: "in the last",
    dateOperatorNotInTheLast: "not in the last",
    dateOperatorIsBetween: "is between",
    dateOperatorIsNotBetween: "is not between",
    dateOperatorIsBlank: "is blank",
    dateOperatorIsNotBlank: "is not blank",
    numberOperatorIs: "is", // e.g. <numberFieldName> is 1000
    numberOperatorIsNot: "is not",
    numberOperatorIsAtLeast: "is at least",
    numberOperatorIsLessThan: "is less than",
    numberOperatorIsAtMost: "is at most",
    numberOperatorIsGreaterThan: "is greater than",
    numberOperatorIsBetween: "is between",
    numberOperatorIsNotBetween: "is not between",
    numberOperatorIsBlank: "is blank",
    numberOperatorIsNotBlank: "is not blank",
    operationalLayerTip:"Add result as operational layer",
    queryResult:"Query Result",
    specifyParamsTip:"Specify parameters for this task",
    useSpatialFilter:"Use spatial filter to limit features",
    useCurrentMapExtent:"Only features touching the current map extent",
    drawGraphicOnMap:"Only features touching a user defined area",
    specifySpatialFilterMsg:"Please specify spatial filter for this task.",
    clearResults: "Clear Results",
    operationalTip:'With this option checked, results will be kept on the map until the "${clearResults}" button clicked.',
    noLayerTip:"There are no pre-configured layers available.",
    noPermissionsMsg:"You do not have permissions to access this service."
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});